FROM node:16 as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine
EXPOSE 3000
COPY ./nginx/default.chttp://104.248.251.120/onf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html