version: '3'
services:



  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - web-root:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      # - certbot-etc:/etc/letsencrypt
      # - certbot-var:/var/lib/letsencrypt
    depends_on:
      - stypendia-server
      - stypendia-front

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - web-root:/var/www/html
  #   depends_on:
  #     - webserver
  #   command: certonly --webroot --webroot-path=/var/www/html --email sammy@example.com --agree-tos --no-eff-email --staging -d example.com  -d www.example.com

  stypendia-front:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    env_file:
      - ./client/.env
    volumes:
      - ./client/build:/app/build

  stypendia-server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    env_file:
      - ./server/.env.prod
    environment:
      - NODE_ENV=production



  db_stypendia:
    env_file:
      - ./server/.env.prod
    volumes:
      - ./server/data/db:/var/lib/mysql

  adminer_stypendia:
    env_file:
      - ./server/.env.prod

  mongo_logs_stypendia:
    env_file:
      - ./server/.env.prod

  mongoweb_logs:
    image: mongo-express
    restart: always
    env_file:
      - ./server/.env.prod
    ports:
      - 8084:8081
    depends_on:
      - mongo_logs_stypendia


volumes:
  node-app-data:
  # certbot-etc:
  # certbot-var:
  web-root:
