version: '3'
services:


  stypendia-front:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    env_file:
      - ./client/.env
    ports:
      - 3002:3002
    volumes:
      - ./client/app
      - react-app-data:/app/node_modules


  stypendia-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    env_file:
      - ./server/.env.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
      - node-app-data:/app/node_modules
    command: npm run devStart


  db_stypendia:
    env_file:
      - ./server/.env.dev
    volumes:
      - ./server/data/db:/var/lib/mysql

  adminer_stypendia:
    env_file:
      - ./server/.env.dev

  mongo_logs_stypendia:
    env_file:
      - ./server/.env.dev

  mongoweb_logs:
    image: mongo-express
    restart: always
    env_file:
      - ./server/.env.dev
    ports:
      - 8084:8081
    depends_on:
      - mongo_logs_stypendia


volumes:
  node-app-data:
  react-app-data: