version: '3'

services:
  stypendia-server:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run devStart
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=8XV4f+dk+MxQD_Qd
      - MYSQL_DATABASE=stypendia_dev
      - MYSQL_USER=tomek
      - MYSQL_PASSWORD=zFh8e^x8Pqxc6b4Q
    volumes:
      - ./data:/data/mysql_typeorm_stypendia_dev

  adminer:
    image: adminer
    restart: always
    env_file:
      - ./.env
    ports:
      - 8085:8085

  redis:
    image: redis:alpine
    hostname: stypendia-server
    restart: always
    ports:
      - 6379:6379

  mongo_logs:
    image: mongo
    ports:
      - 27019:27019
    restart: always
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./data:/data/mongo_logs_stypendia_dev
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  mongoweb_logs:
    image: mongo-express
    restart: always
    env_file:
      - ./.env
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_logs
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 8084:8081
    depends_on:
      - mongo_logs

  # av:
  #debian: image: mkodockx/docker-clamav
  # image: mkodockx/docker-clamav:alpine
  # container_name: nextav
  # restart: unless-stopped
  # ports:
  #   - 3310:3310
#     volumes:
#       - clam:/var/lib/clamav

# volumes:
#   clam:
