version: '3'

services:
  #   stypendia-server:
  #     build:
  #       context: .
  #       args:
  #         NODE_ENV: development
  #     volumes:
  #       - ./:/app
  #       - /app/node_modules
  #     environment:
  #       - NODE_ENV=development
  #     command: npm run devStart
  #     depends_on:
  #       - db_stypendia
  #       - redis_stypendia

  db_stypendia:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 5555:3306

    environment:
      MYSQL_ROOT_PASSWORD: dddd
      MYSQL_DATABASE: dsadsd
      MYSQL_USER: ASasAS
      MYSQL_PASSWORD: serverqwsdqw
    volumes:
      - ./data:/data/mysql_typeorm_stypendia_dev

  adminer_stypendia:
    image: adminer
    restart: always

    ports:
      - 5555:8080
    depends_on:
      - db_stypendia

  redis_stypendia:
    image: redis:alpine
    restart: always

    ports:
      - 5555:6379

  mongo_logs:
    image: mongo
    restart: always
    env_file:
      - ./.env
    ports:
      - 44444:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: OT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: OT_PASSWORD
      MONGO_INITDB_DATABASE: TABASE
      MONGO_USERNAME: ERNAME
      MONGO_PASSWORD: SSWORD
    volumes:
      - ./data:/data/mongo_logs_stypendia_dev
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  mongoweb_logs:
    image: mongo-express
    restart: always
    env_file:
      - ./.env
    environment:
      ME_CONFIG_MONGODB_SERVER:
      ME_CONFIG_MONGODB_ADMINUSERNAME: OT_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: OT_PASSWORD
      ME_CONFIG_BASICAUTH_USERNAME: ERNAME
      ME_CONFIG_BASICAUTH_PASSWORD: SSWORD
    ports:
      - 4444:8081
    depends_on:
      - mongo_logs

  # av:
  #debian: image: mkodockx/docker-clamav
  # image: mkodockx/docker-clamav:alpine
  # container_name: nextav
  # restart: unless-stopped
  # ports:
  #   - 3310:3310
#     volumes:
#       - clam:/var/lib/clamav

# volumes:
#   clam:
