version: '3'

services:
  db_typeorm_stypendia:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: stypendia_dev
      MYSQL_USER: tomek
      MYSQL_PASSWORD: secret
    volumes:
      - ./data:/data/db_typeorm

  adminer_typeorm_stypendia:
    image: adminer
    restart: always
    ports:
      - 8083:8080

  cache_stypendia:
    image: redis:alpine
    restart: always
    ports:
      - 6380:6379

  db_logs:
    image: mongo
    container_name: db_logs
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: logs
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  mongoex:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: db_logs
      # ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    # volumes:
    #   - ./mongoex.sh:/docker-entrypoint.sh
    # env_file:
    #   - .env
    ports:
      - 8084:8081
    depends_on:
      - db_logs
