version: '3'
services:



  # nginx:
  #   image: nginx:stable-alpine
  #   restart: always
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d


  stypendia-front:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    env_file:
      - ./client/.env

  stypendia-server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    env_file:
      - ./server/.env.prod
    environment:
      - NODE_ENV=production



  db_stypendia:
    env_file:
      - ./server/.env.prod
    volumes:
      - ./server/data/db:/var/lib/mysql

  adminer_stypendia:
    env_file:
      - ./server/.env.prod

  mongo_logs_stypendia:
    env_file:
      - ./server/.env.prod

  mongoweb_logs:
    image: mongo-express
    restart: always
    env_file:
      - ./server/.env.prod
    ports:
      - 8084:8081
    depends_on:
      - mongo_logs_stypendia


volumes:
  node-app-data:
