export const SET_USER = 'SET_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHECK_IS_LOGGED_IN = 'CHECK_IS_LOGGED_IN';

export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';

export const GET_SUBMIT = 'GET_SUBMIT';

export const UPDATE_NEW_SUBMIT = 'UPDATE_NEW_SUBMIT';

export const SET_SUBMIT_ID = 'SET_SUBMIT_ID';
export const SET_SUBMIT_MODE = 'SET_SUBMIT_MODE';
export const SET_CUR_SUBMIT = 'SET_CUR_SUBMIT';
export const UPDATE_CUR_SUBMIT = 'UPDATE_CUR_SUBMIT';
export const SET_SUBMIT_TO_WATCH = 'SET_SUBMIT_TO_WATCH';

export const SET_IS_LOADING = 'SET_IS_LOADING';


