export const SET_USER = 'SET_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHECK_IS_LOGGED_IN = 'CHECK_IS_LOGGED_IN';

export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';

export const GET_SUBMIT = 'GET_SUBMIT'

export const UPDATE_CURRENT_SUBMIT = 'UPDATE_CURRENT_SUBMIT'