FROM node:14

WORKDIR /app

COPY package.json ./
RUN npm cache clean --force
RUN npm cache verify
RUN npm install
# w nawiasie jedna spacja z przodu i z tyłu
# RUN if [ "$NODE_ENV" = "development" ]; \
#  then npm install; \
#  else npm install --only production; \
#  fi


COPY . .

ENV PORT 5003

EXPOSE $PORT

CMD ["npm", "run", "build"]