version: '3'
services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d
    depends_on:
      - stypendia-server


  stypendia-server:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
    command: npm run build && npm start



  db_stypendia:
    env_file:
      - .env.prod
    volumes:
      - ./data/db:/var/lib/mysql

  adminer_stypendia:
    env_file:
      - .env.prod

  mongo_logs_stypendia:
    env_file:
      - .env.prod

  mongoweb_logs:
    image: mongo-express
    restart: always
    env_file:
      - .env.prod
    ports:
      - 8084:8081
    depends_on:
      - mongo_logs_stypendia


volumes:
  node-app-data: