version: '3'

services:


  stypendia-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # env_file: ./.env.dev
    ports:
      - 5003:5003
    depends_on:
      - db_stypendia

  db_stypendia:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    volumes:
      - ./data/db:/var/lib/mysql

  adminer_stypendia:
    image: adminer
    restart: always
    ports:
      - 8083:8080
    depends_on:
      - db_stypendia

  redis_stypendia:
    image: redis:alpine
    restart: always
    ports:
      - 6380:6379

  mongo_logs_stypendia:
    image: mongo
    restart: always
    ports:
      - 27019:27017
    volumes:
      - ./data/logs:/var/lib/logs
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  mongoweb_logs:
    image: mongo-express
    restart: always
    ports:
      - 8084:8081
    depends_on:
      - mongo_logs_stypendia


  clamAV:
    image:  mkodockx/docker-clamav:alpine
    restart: always
    ports:
      - 3311:3311
    volumes:
      - ./data/clamav:/var/lib/clamav
# https://github.com/openbridge/clamav
